name: PGMQ Extension

defaults:
  run:
    shell: bash
    working-directory: ./pgmq-extension

on:
  pull_request:
    branches:
      - main
    paths:
      - "pgmq-extension/**"
      - ".github/workflows/extension_ci.yml"
  push:
    branches:
      - main
    paths:
      - "pgmq-extension/**"
      - ".github/workflows/extension_ci.yml"
  release:
    types:
      - created

jobs:
  test:
    name: Test 🐘 ${{ matrix.pg }} with pg_partman ${{ matrix.partman }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        pg: [13, 14, 15, 16, 17]
        partman: [4.7.3, 5.1.0]
        exclude:
          - pg: 13
            partman: 5.1.0
    container: pgxn/pgxn-tools
    steps:
      - run: pg-start ${{ matrix.pg }}
        working-directory: ./
      - uses: actions/checkout@v4
      - run: pgxn install 'pg_partman=${{ matrix.partman }}'
      - run: pg-build-test
